[2025-06-01T23:11:54.732+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-01T23:11:54.874+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-01T23:08:52.895547+00:00 [queued]>
[2025-06-01T23:11:54.883+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-01T23:08:52.895547+00:00 [queued]>
[2025-06-01T23:11:54.885+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-06-01T23:11:54.905+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-06-01 23:08:52.895547+00:00
[2025-06-01T23:11:54.915+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=266) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-01T23:11:54.915+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'manual__2025-06-01T23:08:52.895547+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmp12ed1eti']
[2025-06-01T23:11:54.917+0000] {standard_task_runner.py:72} INFO - Started process 267 to run task
[2025-06-01T23:11:54.918+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask start_spark_consumer
[2025-06-01T23:11:54.949+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T23:11:54.994+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-01T23:08:52.895547+00:00 [running]> on host 2317d0480f96
[2025-06-01T23:11:55.145+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_monitoring_dag' AIRFLOW_CTX_TASK_ID='start_spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T23:08:52.895547+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-01T23:08:52.895547+00:00'
[2025-06-01T23:11:55.147+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-01T23:11:55.169+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-01T23:11:55.170+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            docker run --rm             --network realtime_log_monitoring_default             -v /opt/***/app:/app             bitnami/spark:3.3.0             spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 /app/log_consumer.py\n        ']
[2025-06-01T23:11:55.180+0000] {subprocess.py:86} INFO - Output:
[2025-06-01T23:12:52.894+0000] {job.py:229} INFO - Heartbeat recovered after 27.17 seconds
[2025-06-01T23:13:17.264+0000] {job.py:229} INFO - Heartbeat recovered after 19.32 seconds
[2025-06-01T23:13:51.618+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m23:13:51.21 [0m
[2025-06-01T23:13:51.676+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m23:13:51.61 [0m[1mWelcome to the Bitnami spark container[0m
[2025-06-01T23:13:51.677+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m23:13:51.62 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-06-01T23:13:51.678+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m23:13:51.66 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-06-01T23:13:51.679+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m23:13:51.67 [0m
[2025-06-01T23:13:52.220+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:15:02.365+0000] {job.py:229} INFO - Heartbeat recovered after 12.77 seconds
[2025-06-01T23:15:39.103+0000] {job.py:229} INFO - Heartbeat recovered after 36.96 seconds
[2025-06-01T23:16:00.503+0000] {job.py:229} INFO - Heartbeat recovered after 22.08 seconds
[2025-06-01T23:16:17.430+0000] {job.py:229} INFO - Heartbeat recovered after 11.26 seconds
[2025-06-01T23:16:45.076+0000] {job.py:229} INFO - Heartbeat recovered after 14.25 seconds
[2025-06-01T23:17:16.457+0000] {job.py:229} INFO - Heartbeat recovered after 14.92 seconds
[2025-06-01T23:17:26.851+0000] {job.py:229} INFO - Heartbeat recovered after 11.76 seconds
[2025-06-01T23:17:47.051+0000] {job.py:229} INFO - Heartbeat recovered after 21.62 seconds
[2025-06-01T23:17:58.667+0000] {job.py:229} INFO - Heartbeat recovered after 13.24 seconds
[2025-06-01T23:18:28.172+0000] {job.py:229} INFO - Heartbeat recovered after 18.72 seconds
[2025-06-01T23:18:43.944+0000] {job.py:229} INFO - Heartbeat recovered after 15.91 seconds
[2025-06-01T23:19:07.490+0000] {job.py:229} INFO - Heartbeat recovered after 15.81 seconds
[2025-06-01T23:20:25.714+0000] {job.py:229} INFO - Heartbeat recovered after 19.18 seconds
[2025-06-01T23:20:40.749+0000] {job.py:229} INFO - Heartbeat recovered after 15.19 seconds
[2025-06-01T23:21:14.050+0000] {job.py:229} INFO - Heartbeat recovered after 12.99 seconds
[2025-06-01T23:21:24.798+0000] {job.py:229} INFO - Heartbeat recovered after 10.75 seconds
[2025-06-01T23:21:38.652+0000] {job.py:229} INFO - Heartbeat recovered after 13.86 seconds
[2025-06-01T23:22:03.549+0000] {job.py:229} INFO - Heartbeat recovered after 14.80 seconds
[2025-06-01T23:23:05.517+0000] {job.py:229} INFO - Heartbeat recovered after 53.98 seconds
[2025-06-01T23:23:30.213+0000] {job.py:229} INFO - Heartbeat recovered after 25.69 seconds
[2025-06-01T23:23:56.245+0000] {job.py:229} INFO - Heartbeat recovered after 26.84 seconds
[2025-06-01T23:24:28.694+0000] {job.py:229} INFO - Heartbeat recovered after 25.72 seconds
[2025-06-01T23:24:53.597+0000] {job.py:229} INFO - Heartbeat recovered after 26.27 seconds
[2025-06-01T23:25:29.615+0000] {job.py:229} INFO - Heartbeat recovered after 20.47 seconds
[2025-06-01T23:26:08.071+0000] {job.py:229} INFO - Heartbeat recovered after 40.05 seconds
[2025-06-01T23:26:38.649+0000] {job.py:229} INFO - Heartbeat recovered after 32.02 seconds
[2025-06-01T23:26:55.716+0000] {job.py:229} INFO - Heartbeat recovered after 10.61 seconds
[2025-06-01T23:27:30.735+0000] {job.py:229} INFO - Heartbeat recovered after 14.38 seconds
[2025-06-01T23:28:00.634+0000] {job.py:229} INFO - Heartbeat recovered after 17.13 seconds
[2025-06-01T23:28:41.472+0000] {job.py:229} INFO - Heartbeat recovered after 32.44 seconds
[2025-06-01T23:28:58.594+0000] {job.py:229} INFO - Heartbeat recovered after 17.97 seconds
[2025-06-01T23:29:36.499+0000] {job.py:229} INFO - Heartbeat recovered after 24.62 seconds
[2025-06-01T23:30:03.949+0000] {job.py:229} INFO - Heartbeat recovered after 27.68 seconds
[2025-06-01T23:30:35.431+0000] {job.py:229} INFO - Heartbeat recovered after 31.91 seconds
[2025-06-01T23:31:32.207+0000] {job.py:229} INFO - Heartbeat recovered after 57.52 seconds
[2025-06-01T23:31:42.160+0000] {job.py:229} INFO - Heartbeat recovered after 11.08 seconds
[2025-06-01T23:31:52.659+0000] {job.py:229} INFO - Heartbeat recovered after 10.56 seconds
[2025-06-01T23:32:10.730+0000] {job.py:229} INFO - Heartbeat recovered after 12.10 seconds
[2025-06-01T23:32:30.944+0000] {job.py:229} INFO - Heartbeat recovered after 11.99 seconds
[2025-06-01T23:32:43.852+0000] {job.py:229} INFO - Heartbeat recovered after 13.61 seconds
[2025-06-01T23:32:58.250+0000] {job.py:229} INFO - Heartbeat recovered after 14.97 seconds
[2025-06-01T23:33:06.390+0000] {job.py:229} INFO - Heartbeat recovered after 12.64 seconds
[2025-06-01T23:33:24.762+0000] {job.py:229} INFO - Heartbeat recovered after 20.45 seconds
[2025-06-01T23:33:36.272+0000] {job.py:229} INFO - Heartbeat recovered after 12.55 seconds
[2025-06-01T23:33:35.870+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-01T23:33:41.955+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-06-01T23:33:41.992+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-06-01T23:33:41.993+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-06-01T23:33:41.994+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-1fdf40f5-83cc-4e2a-a065-84471dc13385;1.0
[2025-06-01T23:33:42.022+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-06-01T23:33:54.621+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-01T23:33:54.622+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-01T23:34:04.619+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 28867ms :: artifacts dl 0ms
[2025-06-01T23:34:04.652+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-06-01T23:34:04.774+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T23:34:04.775+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-06-01T23:34:04.791+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-06-01T23:34:05.106+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T23:34:05.107+0000] {subprocess.py:93} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2025-06-01T23:34:05.108+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T23:34:05.108+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.163+0000] {subprocess.py:93} INFO - :: problems summary ::
[2025-06-01T23:34:05.164+0000] {subprocess.py:93} INFO - :::: WARNINGS
[2025-06-01T23:34:05.327+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T23:34:05.328+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.329+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T23:34:05.329+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.330+0000] {subprocess.py:93} INFO - 		module not found: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0
[2025-06-01T23:34:05.331+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.331+0000] {subprocess.py:93} INFO - 	==== local-m2-cache: tried
[2025-06-01T23:34:05.332+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.332+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T23:34:05.333+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.333+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T23:34:05.333+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.334+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T23:34:05.335+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.415+0000] {subprocess.py:93} INFO - 	==== local-ivy-cache: tried
[2025-06-01T23:34:05.434+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.435+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/ivys/ivy.xml
[2025-06-01T23:34:05.436+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.436+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T23:34:05.512+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.513+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/jars/spark-sql-kafka-0-10_2.12.jar
[2025-06-01T23:34:05.513+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.514+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-06-01T23:34:05.514+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.515+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T23:34:05.515+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.515+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T23:34:05.516+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.516+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T23:34:05.517+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.517+0000] {subprocess.py:93} INFO - 	==== spark-packages: tried
[2025-06-01T23:34:05.518+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.518+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T23:34:05.518+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.519+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T23:34:05.519+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.520+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T23:34:05.520+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.521+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-01T23:34:05.521+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.521+0000] {subprocess.py:93} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-06-01T23:34:05.522+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.522+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-01T23:34:05.522+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.523+0000] {subprocess.py:93} INFO - 		:: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found
[2025-06-01T23:34:05.523+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.523+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-01T23:34:05.524+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.524+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.524+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:05.525+0000] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-06-01T23:34:05.525+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found]
[2025-06-01T23:34:05.525+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2025-06-01T23:34:05.526+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-06-01T23:34:05.526+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-06-01T23:34:05.526+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2025-06-01T23:34:05.527+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-06-01T23:34:05.527+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-06-01T23:34:05.527+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-06-01T23:34:05.528+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-06-01T23:34:05.528+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-06-01T23:34:05.528+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-06-01T23:34:28.780+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-01T23:34:45.783+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-01T23:34:53.693+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=log_monitoring_dag, task_id=start_spark_consumer, run_id=manual__2025-06-01T23:08:52.895547+00:00, execution_date=20250601T230852, start_date=20250601T231154, end_date=20250601T233451
[2025-06-01T23:35:00.232+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-01T23:35:00.574+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task start_spark_consumer (Bash command failed. The command returned a non-zero exit code 1.; 267)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-01T23:35:02.611+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-01T23:35:07.231+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-06-01T23:35:20.204+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-01T23:35:20.229+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
